clc; close all; clear;

%% Longitudinal Controller
cd ..\..\..\..\img
addpath(pwd);
cd ..\sim\lon\img\lon

% Load data
equilibrium;
load data;
load dataNL100;

x   = [  50   150   250;
       61.78 176.1 261.8];
   
h   = [-Xe(12) 425 375;
        420    380 395];

v   = [20 20 20;
       20 20 20];

th  = [radtodeg(Xe(8)) radtodeg(Xe(8)) radtodeg(Xe(8));
            7.899          -2.062           7.899];
        
rgb = [0.9290    0.6940    0.1250;
       0.4940    0.1840    0.5560];

a   = ones(size(x));

% co=[  0       0.4470    0.7410
%     0.8500    0.3250    0.0980
%     0.9290    0.6940    0.1250
%     0.4940    0.1840    0.5560
%     0.4660    0.6740    0.1880
%     0.3010    0.7450    0.9330
%     0.6350    0.0780    0.1840];
% 
% %co=get(0, 'DefaultAxesColorOrder');
% set(0,'DefaultAxesColorOrder',co([1 7 5 4 2 6 3],:));

%% Vt
% figure('Units','inches',...
%     'Position',[1 1 7 3],...
%     'PaperPositionMode','auto');
figure('Units','inches',...
    'Position',[1 1 5.04 3.28],...
    'PaperPositionMode','auto');
grid on;
hold on;    

plot( Y.Time, Y.Data(:,1)+norm(Xe(1:3)),'-','LineWidth', 2.0);
plot( NLY.Time, NLY.Data(:,1),'-.','LineWidth', 2.0);

chA = scatter(x(1,:), v(1,:), 200*a(1,:), 'MarkerFaceColor',rgb(1,:), ...
    'MarkerEdgeColor', rgb(1,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
chB = scatter(x(2,:), v(2,:), 200*a(2,:), 'MarkerFaceColor',rgb(2,:), ...
    'MarkerEdgeColor', rgb(2,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);

axis([0 300 19 21]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', 19:0.5:21,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Velocidade Aerodin\^amica (m/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
print -depsc2 lon_vt_beamer.eps    
%% \theta
figure('Units','inches',...
    'Position',[1 1 5.04 3.28],...
    'PaperPositionMode','auto');
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,4)+Xe(8)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,4)), '-.','LineWidth', 2.0);

chA = scatter(x(1,:), th(1,:), 200*a(1,:), 'MarkerFaceColor',rgb(1,:), ...
    'MarkerEdgeColor', rgb(1,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
chB = scatter(x(2,:), th(2,:), 200*a(2,:), 'MarkerFaceColor',rgb(2,:), ...
    'MarkerEdgeColor', rgb(2,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
    
axis([0 300 -5 11]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -5:4:11,...
    'Position',[.15 .2 .75 .7]);

ylabel({'\^Angulo de Arfagem (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;

print -depsc2 lon_theta_beamer.eps
%% h
figure('Units','inches',...
    'Position',[1 1 5.04 3.28],...
    'PaperPositionMode','auto');
grid on;
hold on; 

plot( Y.Time, Y.Data(:,5)-Xe(12), '-','LineWidth', 2.0);
plot( NLY.Time, NLY.Data(:,5), '-.','LineWidth', 2.0);
plot( NLstep.Time, NLstep.Data(:,2), '--k','LineWidth', 1.5);    
scatter(x(1,:), h(1,:), 200*a(1,:), 'MarkerFaceColor',rgb(1,:), ...
    'MarkerEdgeColor', rgb(1,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
scatter(x(2,:), h(2,:), 200*a(2,:), 'MarkerFaceColor',rgb(2,:), ...
    'MarkerEdgeColor', rgb(2,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);

axis([0 300 350 450]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', 350:25:450,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Altitude (m)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear', 'Refer\^encia'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
print -depsc2 lon_h_beamer.eps
%% subplots
subplotB;