%% Longitudinal Controller
figure('Units','inches',...
    'Position',[0 0 7 9],...
    'PaperPositionMode','auto');
%% \theta
subplot(3,1,2);
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,4)+Xe(8)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,4)), '-.','LineWidth', 2.0);

chA = scatter(x(1,:), th(1,:), 200*a(1,:), 'MarkerFaceColor',rgb(1,:), ...
    'MarkerEdgeColor', rgb(1,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
chB = scatter(x(2,:), th(2,:), 200*a(2,:), 'MarkerFaceColor',rgb(2,:), ...
    'MarkerEdgeColor', rgb(2,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);

axis([0 300 -5 11]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -5:4:11);

ylabel({'\^Angulo de Arfagem (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best'); 
%% V_T
subplot(3,1,1);
grid on;
hold on;

plot( Y.Time, Y.Data(:,1)+norm(Xe(1:3)),'-','LineWidth', 2.0);
plot( NLY.Time, NLY.Data(:,1),'-.','LineWidth', 2.0);

chA = scatter(x(1,:), v(1,:), 200*a(1,:), 'MarkerFaceColor',rgb(1,:), ...
    'MarkerEdgeColor', rgb(1,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
chB = scatter(x(2,:), v(2,:), 200*a(2,:), 'MarkerFaceColor',rgb(2,:), ...
    'MarkerEdgeColor', rgb(2,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);

axis([0 300 19 21]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', 19:0.5:21);

ylabel({'Velocidade Aerodin\^amica (m/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');
%% H
subplot(3,1,3);
grid on;
hold on;

plot( Y.Time, Y.Data(:,5)-Xe(12), '-','LineWidth', 2.0);
plot( NLY.Time, NLY.Data(:,5), '-.','LineWidth', 2.0);
plot( NLstep.Time, NLstep.Data(:,2), '--k','LineWidth', 1.5);    
scatter(x(1,:), h(1,:), 200*a(1,:), 'MarkerFaceColor',rgb(1,:), ...
    'MarkerEdgeColor', rgb(1,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);
scatter(x(2,:), h(2,:), 200*a(2,:), 'MarkerFaceColor',rgb(2,:), ...
    'MarkerEdgeColor', rgb(2,:), 'MarkerFaceAlpha',.35,'MarkerEdgeAlpha',.35);

axis([0 300 362.5 437.5]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', 362.5:12.5:437.5);

ylabel({'Altitude (m)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear', 'Refer\^encia'},...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
%%
print -depsc2 lon_subplot.eps 
%samexaxis('join','ytac','xmt','off', 'yld', 1)
%%