%% Trajectory B
figure('Units','inches',...
    'Position',[0 0 7 10],...
    'PaperPositionMode','auto');
%% \phi
subplot(3,1,1);
grid on;
hold on;

plot( embY.Time, radtodeg((embY.Data(:,7))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -50 50]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -50:25:50);

ylabel({'\^Angulo de Rolamento (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

% legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
%     'FontUnits', 'points',...
%     'interpreter', 'latex',...
%     'FontSize', 10,...
%     'FontName', 'Times New Roman',...
%     'Location', 'Best'); 
%% \theta
subplot(3,1,2);
grid on;
hold on;

plot( embY.Time, radtodeg((embY.Data(:,8))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -9 15]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -9:6:15);

ylabel({'\^Angulo de Arfagem (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

% legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
%     'FontUnits', 'points',...
%     'interpreter', 'latex',...
%     'FontSize', 10,...
%     'FontName', 'Times New Roman',...
%     'Location', 'Best');
%% \psi
subplot(3,1,3);
grid on;
hold on;

plot( step.Time, radtodeg((step.Data(:,3))), '-', 'LineWidth', 2.0, ...
      'Color', [0.8500 0.3250 0.0980]);
plot( embY.Time, radtodeg((embY.Data(:,9))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 0 400]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', 0:100:400);

ylabel({'\^Angulo de Guinada (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'\^Angulo de Refer\^encia', 'Resposta Obtida'}, ...
     'FontUnits', 'points',...
     'interpreter', 'latex',...
     'FontSize', 10,...
     'FontName', 'Times New Roman',...
     'Location', 'Best');   
hold off;
%%
print -depsc2 trajC_subplotC.eps 