%% Trajectory B
figure('Units','inches',...
    'Position',[0 0 7 10],...
    'PaperPositionMode','auto');
%% \delta_T
% subplot(4,1,1);
% grid on;
% hold on;
% 
% plot( embU.Time, 100*(embU.Data(:,1)), ':', 'LineWidth', 2.0, ...
%       'Color', [0 0.4470 0.7410]);
% 
% axis([0 400 -12 20]);
% set(gca, ...
%     'Units', 'normalized',...        
%     'FontUnits', 'points',...
%     'FontWeight', 'normal',...
%     'FontSize', 10,...
%     'FontName', 'Times New Roman',...
%     'XTick', 0:50:400,...
%     'YTick', -12:8:20);
% 
% ylabel({'Posi\c{c}\~ao Manete (por cento)'}, ...
%     'FontUnits', 'points',...
%     'interpreter', 'latex',...
%     'FontWeight', 'normal',...
%     'FontSize', 10.5,...
%     'FontName', 'Times New Roman');
%% \delta_e
subplot(3,1,1);
grid on;
hold on;

plot( embU.Time, radtodeg(embU.Data(:,2)), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -12 4]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -12:4:4);

ylabel({'Deflex\~ao Profundor (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');
%% \delta_a
subplot(3,1,2);
grid on;
hold on;

plot( embU.Time, radtodeg(embU.Data(:,3)), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -10 10]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -10:5:10);

ylabel({'Deflex\~ao Ailerons (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');
%% delta_r
subplot(3,1,3);
grid on;
hold on;

plot( embU.Time, radtodeg(embU.Data(:,4)), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -2 2]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -2:1:2);

ylabel({'Deflex\~ao Leme (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');  
hold off;
%%
print -depsc2 trajC_subplotD.eps 