clc; close all; clear;

%% Longitudinal Controller
cd ..\..\..\img
addpath(pwd);
cd ..\sim\lon\emb

% Load data
equilibrium;
load dataNL100;
load dataEMB100;

rgb = [0.8500    0.3250    0.0980;
       0.4660    0.6740    0.1880];

% co=[  0       0.4470    0.7410
%     0.8500    0.3250    0.0980
%     0.9290    0.6940    0.1250
%     0.4940    0.1840    0.5560
%     0.4660    0.6740    0.1880
%     0.3010    0.7450    0.9330
%     0.6350    0.0780    0.1840];
% 
% %co=get(0, 'DefaultAxesColorOrder');
% set(0,'DefaultAxesColorOrder',co([1 7 5 4 2 6 3],:));

%% Vt
% figure('Units','inches',...
%     'Position',[1 1 7 3],...
%     'PaperPositionMode','auto');
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on;

plot( NLY.Time, NLY.Data(:,1),'-', 'LineWidth', 2.0);
plot( EMB_Y.Time, EMB_Y.Data(:,1),':', 'LineWidth', 2.0);

axis([0 300 19 21]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', 19.0:0.5:21.0,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Velocidade Aerodin\^amica (m/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta N\~ao Linear', 'Resposta Discreta'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
print -depsc2 lon_emb_vt_beamer.eps    
%% \theta
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on;

plot( NLY.Time, radtodeg(NLY.Data(:,4)), '-', 'LineWidth', 2.0);
plot( EMB_Y.Time, radtodeg(EMB_Y.Data(:,4)), ':', 'LineWidth', 2.0);
    
axis([0 300 -5 11]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -5:4:11,...
    'Position',[.15 .2 .75 .7]);

ylabel({'\^Angulo de Arfagem (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta N\~ao Linear', 'Resposta Discreta',}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;

print -depsc2 lon_emb_theta_beamer.eps
%% h
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on; 

plot( NLY.Time, NLY.Data(:,5), '-', 'LineWidth', 2.0);
plot( EMB_Y.Time, EMB_Y.Data(:,5), ':', 'LineWidth', 2.0);
plot( EMBstep.Time, EMBstep.Data(:,2), '--k','LineWidth', 1.5); 

axis([0 300 362.5 437.5]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', 362.5:12.5:437.5,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Altitude (m)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta N\~ao Linear', 'Resposta Discreta', 'Refer\^encia'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
print -depsc2 lon_emb_h_beamer.eps
%% subplots
subplotB;