clc; close all; clear;

%% UCP
cd ..\..\..\..\img
addpath(pwd);
cd ..\sim\ucp\img\sim05

% Load data
equilibrium;
load dataEMB100;
load dataNL100;

% co=[  0       0.4470    0.7410
%     0.8500    0.3250    0.0980
%     0.9290    0.6940    0.1250
%     0.4940    0.1840    0.5560
%     0.4660    0.6740    0.1880
%     0.3010    0.7450    0.9330
%     0.6350    0.0780    0.1840];
% 
% %co=get(0, 'DefaultAxesColorOrder');
% set(0,'DefaultAxesColorOrder',co([1 7 5 4 2 6 3],:));

%% Trajectory
% figure('Units','inches',...
%     'Position',[1 1 7 5],...
%     'PaperPositionMode','auto');
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on;    

plot( WP(1,:), WP(2,:), '-', 'LineWidth', 2.0, ...
      'Color', [0.8500 0.3250 0.0980]);
plot( embY.Data(:,10), embY.Data(:,11), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([-1000 1500 -1000 1000]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', -1000:500:1500,...
    'YTick', -1000:500:1000,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Leste (m)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Norte (m)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

for i=1:size(WP,2)    
    wp = WP(1:2, i);
    plot(wp(1), wp(2), 'kx', 'LineWidth', 2.0);
    
    if i==size(WP,2)
        text(wp(1), wp(2), sprintf('\n\n   WP %s', num2str(i)), ...
        'FontWeight', 'bold',...
        'FontSize', 9,...
        'FontName', 'Times New Roman');
    else
        text(wp(1), wp(2), ['   WP ' num2str(i)], ...
        'FontWeight', 'bold',...
        'FontSize', 9,...
        'FontName', 'Times New Roman');
    end    
end

legend({'Trajetoria Ideal', 'Trajetoria Percorrida'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'southeast');   
hold off;
print -depsc2 trajB_beamer.eps    
%% \Vt
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on;

plot( step.Time, step.Data(:,1), '-', 'LineWidth', 2.0, ...
      'Color', [0.8500 0.3250 0.0980]);
plot( embY.Time, embY.Data(:,1), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);
    
axis([0 600 16 24]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:100:600,...
    'YTick', 16:2:24.,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Velocidade Aerodin\^amica (m/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Velocidade de Refer\^encia', 'Resposta Obtida'}, ...
     'FontUnits', 'points',...
     'interpreter', 'latex',...
     'FontSize', 10,...
     'FontName', 'Times New Roman',...
     'Location', 'Best');   
hold off;
print -depsc2 trajB_vt_beamer.eps
%% H
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on; 

plot( step.Time, step.Data(:,02), '-', 'LineWidth', 2.0, ...
      'Color', [0.8500 0.3250 0.0980]);
plot( embY.Time, embY.Data(:,12), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 600 370 430]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:100:600,...
    'YTick', 370:10:430,...
    'Position',[.15 .2 .75 .7]);

ylabel({'Altitude (m)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Altitude de Refer\^encia', 'Resposta Obtida'}, ...
     'FontUnits', 'points',...
     'interpreter', 'latex',...
     'FontSize', 10,...
     'FontName', 'Times New Roman',...
     'Location', 'Best');   
hold off;
print -depsc2 trajB_h_beamer.eps
%% \psi
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on; 

plot( step.Time, radtodeg((step.Data(:,3))), '-', 'LineWidth', 2.0, ...
      'Color', [0.8500 0.3250 0.0980]);
plot( embY.Time, radtodeg((embY.Data(:,9))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 600 0 800]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:100:600,...
    'YTick', 0:200:800,...
    'Position',[.15 .2 .75 .7]);

ylabel({'\^Angulo de Guinada (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'\^Angulo de Refer\^encia', 'Resposta Obtida'}, ...
     'FontUnits', 'points',...
     'interpreter', 'latex',...
     'FontSize', 10,...
     'FontName', 'Times New Roman',...
     'Location', 'Best');   
hold off;
print -depsc2 trajB_psi_beamer.eps
%% subplots
%subplotB;