clc; close all;

%% Heading Hold
cd ..\..\..\..\img
addpath(pwd);
cd ..\sim\lat\img\yaw
%%

%% Load data
load data;
load dataNL100;

% Carrega entradas e estados de equilibrio;
equilibrium;

%% \phi
% figure('Units','inches',...
%     'Position',[1 1 7 3],...
%     'PaperPositionMode','auto');
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,4)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,4)), '-.','LineWidth', 2.0); 
    
axis([0 300 -30 30]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -30:15:30,...
    'Position',[.15 .2 .75 .7]);

ylabel({'\^Angulo de Rolamento (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;

print -depsc2 lat_phi_beamer.eps  
% %% \psi
% figure('Units','inches',...
%     'Position',[1 1 7 3],...
%     'PaperPositionMode','auto');
figure('Units','inches',...
    'Position',[1 1 5.04 3.78],...
    'PaperPositionMode','auto');
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,5)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,5)), '-.','LineWidth', 2.0);     
plot( NLstep.Time, radtodeg(NLstep.Data), '--k','LineWidth', 1.5); 
    
axis([0 300 -50 50]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -50:25:50,...
    'Position',[.15 .2 .75 .7]);

ylabel({'\^Angulo de Guinada (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear', 'Refer\^encia'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;

print -depsc2 lat_psi_beamer.eps  
%% subplot
subplotB;

