
%% Heading Hold
figure('Units','inches',...
    'Position',[0 0 7 6],...
    'PaperPositionMode','auto');
%% \phi
subplot(2,1,1);
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,4)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,4)), '-.','LineWidth', 2.0); 

axis([0 300 -30 30]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -30:15:30);

ylabel({'\^Angulo de Rolamento (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
%% \psi
subplot(2,1,2);
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,5)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,5)), '-.','LineWidth', 2.0);     
plot( NLstep.Time, radtodeg(NLstep.Data), '--k','LineWidth', 1.5); 
    
axis([0 300 -50 50]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:300,...
    'YTick', -50:25:50);

ylabel({'\^Angulo de Guinada (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear', 'Refer\^encia'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
%%
print -depsc2 lat_subplot.eps 
% samexaxis('xmt','off','ytac','yld', 1, 'box', 'on')
% samexaxis('ytac','join','xmt','off', 'yld', 1.0)