%% Trajectory B
figure('Units','inches',...
    'Position',[0 0 7 10],...
    'PaperPositionMode','auto');
%% \p
subplot(3,1,1);
grid on;
hold on;

plot( embY.Time, radtodeg((embY.Data(:,4))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -45 45]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -45:15:45);

ylabel({'Vel. Angular de Rolamento (graus/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

% legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
%     'FontUnits', 'points',...
%     'interpreter', 'latex',...
%     'FontSize', 10,...
%     'FontName', 'Times New Roman',...
%     'Location', 'Best'); 
%% q
subplot(3,1,2);
grid on;
hold on;

plot( embY.Time, radtodeg((embY.Data(:,5))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -40 40]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -40:20:40);

ylabel({'Vel. Angular de Arfagem (graus/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

% legend([chA chB], {'Chaveamento A', 'Chaveamento B'}, ...
%     'FontUnits', 'points',...
%     'interpreter', 'latex',...
%     'FontSize', 10,...
%     'FontName', 'Times New Roman',...
%     'Location', 'Best');
%% r
subplot(3,1,3);
grid on;
hold on;

plot( embY.Time, radtodeg((embY.Data(:,6))), ':', 'LineWidth', 2.0, ...
      'Color', [0 0.4470 0.7410]);

axis([0 400 -30 20]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:50:400,...
    'YTick', -30:10:20);

ylabel({'Vel. Angular de Guinada (graus/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

% legend({'Resposta Linear', 'Resposta N\~ao-Linear', 'Refer\^encia'},...
%     'FontUnits', 'points',...
%     'interpreter', 'latex',...
%     'FontSize', 10,...
%     'FontName', 'Times New Roman',...
%     'Location', 'Best');   
hold off;
%%
print -depsc2 trajC_subplotB.eps 