%% Pitch Attitude plus Speed Hold 
figure('Units','inches',...
    'Position',[0 0 7 10],...
    'PaperPositionMode','auto');
%% \theta
subplot(3,1,2);
grid on;
hold on;

plot( Y.Time, radtodeg(Y.Data(:,4)+Xe(8)), '-','LineWidth', 2.0);
plot( NLY.Time, radtodeg(NLY.Data(:,4)), '-.','LineWidth', 2.0);
plot( NLstep.Time, radtodeg(NLstep.Data(:,2)), '--k','LineWidth', 1.5);

axis([0 60 2 10]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:10:60,...
    'YTick', 2:2:10);

ylabel({'\^Angulo de Arfagem (graus)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear', 'Refer\^encia'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best'); 
%% V_T
subplot(3,1,1);
grid on;
hold on;

plot( Y.Time, Y.Data(:,1)+norm(Xe(1:3)),'-','LineWidth', 2.0);
plot( NLY.Time, NLY.Data(:,1),'-.','LineWidth', 2.0);
plot( NLstep.Time, NLstep.Data(:,1), '--k','LineWidth', 1.5);

axis([0 60 19 20.25]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:10:60,...
    'YTick', 19:0.25:20.25);

ylabel({'Velocidade Aerodin\^amica (m/s)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'normal',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear', 'Refer\^encia'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');
%% H
subplot(3,1,3);
grid on;
hold on;

plot( Y.Time, Y.Data(:,5)-Xe(12), '-','LineWidth', 2.0);    
plot( NLY.Time, NLY.Data(:,5), '-.','LineWidth', 2.0);

axis([0 60 400 470]);
set(gca, ...
    'Units', 'normalized',...        
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'XTick', 0:10:60,...
    'YTick', 400:17.5:470);

ylabel({'Altitude (m)'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

xlabel('Tempo (s)',...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontWeight', 'bold',...
    'FontSize', 10.5,...
    'FontName', 'Times New Roman');

legend({'Resposta Linear', 'Resposta N\~ao Linear'}, ...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', 10,...
    'FontName', 'Times New Roman',...
    'Location', 'Best');   
hold off;
%%
print -depsc2 spd_subplot.eps 
%samexaxis('join','ytac','xmt','off', 'yld', 1)
%%